/**:
  ros__parameters:
    inputs: ['ground_truth_cloud']
    ground_truth_cloud: # A name to identify the input source
      type: pointcloud # Supported types: pointcloud
      topic: /velodyne_points
      queue_size: 10
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
    map_frame_id: "map-centric"
    robot_base_frame_id: "base_link"
    robot_pose_with_covariance_topic: "lio_sam/mapping/odometry"
    track_point_frame_id: "map-centric"
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
